name: Build Docker and upload to dockerhub

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Verify Changed files
        uses: tj-actions/changed-files@v36
        id: changed-files
        with:
          since_last_remote_commit: true
          files: |
             scripts/image

      - name: Build and push docker
        if: steps.changed-files.outputs.any_changed == 'true'
        shell: bash
        run: |
          split=(${GITHUB_REF_NAME//-/ })
          MATRIX_DOCKER_IMAGE=$(cat scripts/image)
          
          if ! docker manifest inspect ${MATRIX_DOCKER_IMAGE}
          then
            docker build ./scripts -t ${MATRIX_DOCKER_IMAGE}
            docker push ${MATRIX_DOCKER_IMAGE}
          fi
